services:
  polaris:
    build:
        context: .
        dockerfile: Dockerfile.polaris
    image: ghcr.io/kameshsampath/polaris-spark-devbox/polaris:sha-66c3563-java21
    pull_policy: always
    container_name: polaris
    ports:
      - "10081:8181"
      - "10082:8182"
    networks:
        spark-iceberg:
    env_file:
      - .env
    volumes:
      # any hadoop properties can be configured in the cross-site.xml
      # this mount /conf will be added to classpath
      - ./conf:/conf
      - iceberg-data:/data
      # todo mount the polaris-server.yml if needed to update the config
  spark:
    image: ghcr.io/kameshsampath/polaris-spark-devbox/spark35notebook:sha-66c3563-java17-spark3.5.4-hadoop3
    pull_policy: always
    ports: 
      - 8888:8888  # Notebook
    env_file:
      - .env
    container_name: spark
    user: jovyan
    volumes:
      # make local copy of the notebooks
      - notebooks-data:/home/jovyan/work
      # use local nexus as maven mirror for ivy
      - ./conf:/conf
      - iceberg-data:/data
    networks:
        spark-iceberg:
    depends_on:
    - polaris
networks:
  spark-iceberg:
volumes:
    iceberg-data:
        name: iceberg-data
    notebooks-data:
        name: notebooks-data