# polaris catalog API host and port
@apiHost = localhost
@apiPort = 10081
# polaris catalog API base URI
@baseURI = http://{{apiHost}}:{{apiPort}}/api/management/v1
# root credentials for polaris catalog API request
@clientID = ada6fb08e4ded0d1
@clientSecret = 8d12887a8c0d2d51feea9dc80f458e5b

# Get Auth Token
# Get an access token using the client credentials grant type.
POST http://{{apiHost}}:{{apiPort}}/api/catalog/v1/oauth/tokens
content-type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_id={{clientID}}
&client_secret={{clientSecret}}
&scope=PRINCIPAL_ROLE:ALL
